Version 0.3 beta
encode/typesystem pull request #98
Opened 2020-03-27 11:45 UTC by tomchristie

2021-08-18 13:55 UTC, tomchristie commented
@aminalaee When you're ready to roll a release, you'll want to create a release draft that we can check over...

<img width="733" alt="Screenshot 2021-08-18 at 14 51 04" src="https://user-images.githubusercontent.com/647359/129910652-fb5e7ad0-db2f-47bb-afc1-c45ac9cabc1a.png">

<img width="977" alt="Screenshot 2021-08-18 at 14 51 20" src="https://user-images.githubusercontent.com/647359/129910660-43f7bf5c-1d25-472d-8895-8a6caec7a191.png">

Once we're happy with that, we can:

* Merge the new version pull request...
* ...then publish the release.

2021-08-18 15:52 UTC, aminalaee commented
@tomchristie Thank you. I'm a little confused now.
Do we want to merge this beta version into master now? Shouldn't we publish beta releases `0.3.0.devX` of this branch instead of master, and when it's ready merge into master and close this PR and publish `0.3.0`?

2021-08-31 10:45 UTC, tomchristie commented
@aminalaee - So I wasn't sure of the answer to that question. The sensible thing here is "do whatever we're currently already doing". I'd assumed `master` branch was on 0.3.0.dev0, but [I can see now that's not the case](https://github.com/encode/typesystem/blob/master/typesystem/__init__.py), and that 0.3 pre-releases are [maintained on a separate branch](https://github.com/encode/typesystem/blob/version-0.3-beta/typesystem/__init__.py).

> Shouldn't we keep this branch, publish beta releases 0.3.0.devX of this instead of master, and when it's ready, merge into master and close this PR and publish 0.3.0?

Yes that would make sense.

2021-09-14 09:28 UTC, aminalaee requested changes

2021-09-14 09:28 UTC, aminalaee commented on docs/forms.md
> +        <input type="date" id="" name="end_date" required >
`id` and `label` fields are empty.

2021-09-14 11:54 UTC, aminalaee commented on docs/forms.md
> +        <input type="date" id="" name="end_date" required >
Added `label` and `id` without prefix

2021-09-15 10:49 UTC, aminalaee commented
https://github.com/encode/typesystem/releases/edit/untagged-a8553b8dccc475111fef

2021-09-15 10:51 UTC, aminalaee approved these changes

2021-09-15 10:52 UTC, merged